# Generated by Django 4.0.1 on 2024-04-01 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(upload_to='image')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('short_bio', models.TextField(blank=True, max_length=250, verbose_name='Short Bio')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='source')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
