# Generated by Django 4.0.1 on 2024-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='source',
            field=models.CharField(blank=True, max_length=50, verbose_name='source'),
        ),
    ]
