# Generated by Django 4.0.1 on 2024-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True, max_length=50, verbose_name='Short Bio'),
        ),
    ]
