# Generated by Django 4.0.1 on 2024-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_address_profile_age_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='defualt.jpg', upload_to='profile_banners'),
        ),
    ]
