# Generated by Django 4.0.1 on 2024-04-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_bio',
        ),
    ]
