# Generated by Django 4.0.1 on 2024-04-12 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GamesLibrary', '0007_rename_generalinfo_customgame_general_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgame',
            name='user',
        ),
        migrations.AddField(
            model_name='customgame',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
