# Generated by Django 4.0.1 on 2024-04-12 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GamesLibrary', '0008_remove_customgame_user_customgame_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgame',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
