# Generated by Django 4.0.1 on 2024-04-12 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0009_alter_customgame_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgame',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customgame',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='customgame',
            name='prototype_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
