# Generated by Django 4.0.1 on 2024-04-12 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GamesLibrary', '0010_customgame_payment_customgame_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgame',
            name='user',
        ),
        migrations.AddField(
            model_name='customgame',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
