# Generated by Django 4.0.1 on 2024-04-14 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0011_remove_customgame_user_customgame_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customgame',
            name='game_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('concept', 'Concept'), ('prototyping', 'Prototyping'), ('alpha', 'Alpha Version'), ('beta', 'Beta Version'), ('playtesting', 'Playtesting'), ('polishing', 'Polishing'), ('final_testing', 'Final Testing'), ('marketing', 'Marketing'), ('launch', 'Launch'), ('post_launch_support', 'Post-launch Support')], default='draft', max_length=20),
        ),
    ]
