# Generated by Django 4.0.1 on 2024-04-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0012_customgame_created_at_game_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='GamesLibrary.Platforms'),
        ),
    ]
