# Generated by Django 4.0.1 on 2024-04-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0013_platforms_game_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='game_pics'),
        ),
    ]
