# Generated by Django 4.0.1 on 2024-04-15 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GamesLibrary', '0014_alter_game_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritegames',
            unique_together={('user', 'game')},
        ),
    ]
