# Generated by Django 4.0.1 on 2024-04-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0015_alter_favoritegames_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
    ]
