# Generated by Django 4.0.1 on 2024-04-17 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0016_remove_game_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Game',
            new_name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
