# Generated by Django 4.0.1 on 2024-04-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0017_rename_game_cartitem_game_game_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
