# Generated by Django 4.0.1 on 2024-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0019_order_orderitem_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='genres_pics'),
        ),
    ]
