# Generated by Django 4.0.1 on 2024-04-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0022_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgame',
            name='Platforms',
            field=models.ManyToManyField(to='GamesLibrary.Platforms'),
        ),
    ]
