# Generated by Django 4.0.1 on 2024-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0023_customgame_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_requirments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
