# Generated by Django 4.0.1 on 2024-04-24 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0024_game_game_requirments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgame',
            name='order_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
