# Generated by Django 4.0.1 on 2024-04-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0026_customgame_completed_alter_mygames_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
