# Generated by Django 4.0.1 on 2024-04-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0027_game_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritegames',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mygames',
            unique_together=set(),
        ),
    ]
