# Generated by Django 4.0.1 on 2024-05-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0028_alter_favoritegames_unique_together_and_more'),
    ]

    operations = [
        
        
    ]
