# Generated by Django 4.0.1 on 2024-05-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0029_remove_mygames_game_mygames_games'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='favoritegames',
            name='game',
        ),
        migrations.AddField(
            model_name='favoritegames',
            name='game',
            field=models.ManyToManyField(to='GamesLibrary.Game'),
        ),
    ]
