# Generated by Django 4.0.1 on 2024-06-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0031_remove_mygames_game_mygames_games_report'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='report',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamesLibrary.game'),
        ),
    ]
